# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudenelson < Formula
  desc "Terminal block-based text editor like Notion"
  homepage "https://github.com/leandroBorgesFerreira/Claudenelson"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leandroBorgesFerreira/Claudenelson/releases/download/v0.6.0/claudenelson_0.6.0_darwin_amd64.tar.gz"
      sha256 "47cd9be2553ac2623a109ca05b3820ac18a264d5da19e3bfb0e18f914b95d250"

      define_method(:install) do
        bin.install "claudenelson"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leandroBorgesFerreira/Claudenelson/releases/download/v0.6.0/claudenelson_0.6.0_darwin_arm64.tar.gz"
      sha256 "23d65f1bc8483feed3b1dc6ffe4a62471427c6d2f5582078a6b0edb8dfe1f2bc"

      define_method(:install) do
        bin.install "claudenelson"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leandroBorgesFerreira/Claudenelson/releases/download/v0.6.0/claudenelson_0.6.0_linux_amd64.tar.gz"
      sha256 "0fe92cb6e4ae29c9da034c528f2df409e721bef89e90fc51a9f695a065317d5c"
      define_method(:install) do
        bin.install "claudenelson"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leandroBorgesFerreira/Claudenelson/releases/download/v0.6.0/claudenelson_0.6.0_linux_arm64.tar.gz"
      sha256 "fc95da9d6f58a4666262c7595f667e909d13db0aa0c4c98ca75b9c41fa639a1f"
      define_method(:install) do
        bin.install "claudenelson"
      end
    end
  end
end
