# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudenelson < Formula
  desc "Terminal block-based text editor like Notion"
  homepage "https://github.com/leandroBorgesFerreira/Claudenelson"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leandroBorgesFerreira/Claudenelson/releases/download/v0.2.0/claudenelson_0.2.0_darwin_amd64.tar.gz"
      sha256 "61d3f4a65781376442cacc6fc521697f100da6c783053fbdcb8efc3dfa9cb686"

      define_method(:install) do
        bin.install "claudenelson"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leandroBorgesFerreira/Claudenelson/releases/download/v0.2.0/claudenelson_0.2.0_darwin_arm64.tar.gz"
      sha256 "cd0a7bd5b8dbe3eaf992aef4967f5a2de7746163fe4bb409f5d944076752a5f9"

      define_method(:install) do
        bin.install "claudenelson"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leandroBorgesFerreira/Claudenelson/releases/download/v0.2.0/claudenelson_0.2.0_linux_amd64.tar.gz"
      sha256 "7a45588fa5cc96b81a1cbbb0fe27052f614af8acb23604c8453e9d4d28290a5a"
      define_method(:install) do
        bin.install "claudenelson"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leandroBorgesFerreira/Claudenelson/releases/download/v0.2.0/claudenelson_0.2.0_linux_arm64.tar.gz"
      sha256 "f167dab3d4c2752f119da43674233bcc194e6e9a59e230a00834a4c50221b3b1"
      define_method(:install) do
        bin.install "claudenelson"
      end
    end
  end
end
